# Name of your site. Used to uniquely configure containers.
service: artesliberales

# Name of the container image.
image: hermeneumata/artesliberales

# Deploy to these servers.
servers:
  - 91.99.69.84

proxy:
  ssl: true
  hosts: 
    - artesliberales.org

# Use GIT_URL from env to auto-update site via git pulls.
# Remember to run `kamal env push` after making changes!
env:
  secret:
    - GIT_URL

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: hermeneumata

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Use a different ssh user than root
# ssh:
#   user: app
builder:
  arch: amd64